#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#

DIRNAME=$(dirname "$0")
APP_BASE_NAME=$(basename "$0")
APP_HOME=$(cd "$DIRNAME" && pwd)

# Resolve links
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=$(ls -ld "$PRG")
        link=$(expr "$ls" : '.*-> \(.*\)$')
            if expr "$link" : '/.*' > /dev/null; then
                    PRG="$link"
                        else
                                PRG=$(dirname "$PRG")"/$link"
                                    fi
                                    done

                                    GRADLE_USER_HOME=${GRADLE_USER_HOME:-$HOME/.gradle}
                                    DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
                                    CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

                                    exec java $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
                                        -classpath "$CLASSPATH" \
                                            org.gradle.wrapper.GradleWrapperMain "$@"
                                            