version: '1.0'
name: 'android-build-release'
displayName: 'Android 构建发版'
triggers:
  push:
      branches:
            prefix:
                    - ''

                    stages:
                      - name: stage_build
                          displayName: 构建
                              strategy: naturally
                                  trigger: auto
                                      executor: []
                                          steps:
                                                - step: build@gradle
                                                        name: build_gradle
                                                                displayName: Gradle 构建
                                                                        gradleVersion: '7.6'
                                                                                jdkVersion: '11'
                                                                                        commands:
                                                                                                  - chmod +x ./gradlew
                                                                                                            - ./gradlew assembleRelease
                                                                                                                    artifacts:
                                                                                                                              - name: APK_RELEASE
                                                                                                                                          path:
                                                                                                                                                        - app/build/outputs/apk/release/*.apk
                                                                                                                                                                caches:
                                                                                                                                                                          - ~/.gradle/caches
                                                                                                                                                                                    - ~/.gradle/wrapper
                                                                                                                                                                                            notify: []
                                                                                                                                                                                                    strategy:
                                                                                                                                                                                                              retry: '0'

                                                                                                                                                                                                                - name: stage_release
                                                                                                                                                                                                                    displayName: 发版
                                                                                                                                                                                                                        strategy: naturally
                                                                                                                                                                                                                            trigger: auto
                                                                                                                                                                                                                                executor
                                                                                                                                                                                                                                