version: '1.0'
name: 'build-apk'
displayName: '构建APK'
triggers:
  push:
      branches:
            - master

            stages:
              - name: 'build'
                  displayName: '构建'
                      executor: []
                          steps:
                                - step: shell@bash
                                        name: 'gradle_build'
                                                displayName: 'Gradle构建'
                                                        commands:
                                                                  - chmod +x ./gradlew
                                                                            - ./gradlew assembleRelease
                                                                            