名字: Build APK

在:
推:
分支: [掌握,主要的]
工作流_调度:

工作:
建设:
连续运行: Ubuntu-最新版

步伐:
      - 使用: 动作/签出@v4

      - 名字: 建立JDK 17号
使用: 操作/设置-java@v4
随着:
java版本: '17'
分布: 特穆林

      # 【修改点】这里换成了新的设置-梯度动作
      - 名字: 设置梯度
使用: gradle/actions/setup-gradle@v3

      - 名字: 构建调试APK
奔跑: 。/grad Lew组装的bug

      - 名字: 上传APK
使用: 动作/上传-工件@v4
随着:
名字: 应用程序-调试-apk
小路: 应用程序/构建/输出/apk/调试/应用程序调试。apk

